# 后端 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2  # 2个副本提高可用性
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: <你的镜像仓库>/backend:latest  # 后续由CI/CD动态替换
          ports:
            - containerPort: 8081
          # 环境变量（若后端配置中数据库地址为mysql:3306，无需修改）
          # 健康检查（确保后端连接MySQL后就绪）
          readinessProbe:
            httpGet:
              path: /actuator/health  # 若SpringBoot有健康检查端点
              port: 8081
            initialDelaySeconds: 60  # 给MySQL启动时间
            periodSeconds: 10

---
# 后端 Service（内部访问，供前端调用）
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8081
      targetPort: 8081