# 后端 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          # 关键修改：镜像地址替换为实际Docker Hub地址
          image: yangshengzhou/lucky-sms-backend:latest  # 用户名/仓库名:标签（和Docker Hub一致）
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              # 注意：如果你的SpringBoot应用没有actuator健康检查，需要删除这部分或改为实际端点
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10

---
# 后端 Service（无需修改，保持原样）
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8081
      targetPort: 8081