# 后端 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          # 关键修改：替换为 ACR 的完整镜像地址
          image: crpi-kczczesrmgxok6ke.cn-hangzhou.personal.cr.aliyuncs.com/yangshengzhou/lucky-sms-backend:latest  # ACR 地址+仓库名+标签
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /actuator/health  # 确保后端应用有这个健康检查端点，否则删除或修改
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10

---
# 后端 Service（无需修改）
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8081
      targetPort: 8081