server:
  port: 8081
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8

logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/Lucky_SMS?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    charset: UTF-8
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd
    generator:
      escape-non-ascii: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yangshengzhou.lucky_sms.entity
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: 3f7d2a9b5e8c1d4f6h0j2k7m9n1p3q5r8t0v2x4y6z8b0d2f4h6j8l0n2p
  expiration: 86400000
