name: 自动部署服务到k8s集群
on:
  push:
    branches: [ master ]  # 触发分支为master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      # 步骤1：登录到阿里ACR镜像仓库
      - name: 登录ACR镜像仓库
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}  # ACR的访问凭证密码

      # 后端编译打包（生成JAR包）
      - name: 配置Java环境（用于Maven编译）
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: 用Maven编译后端代码生成JAR包
        run: mvn clean package -DskipTests
        working-directory: ./backend

      # 步骤2：构建并推送后端镜像（核心修改2：ACR镜像标签格式）
      - name: 构建后端镜像
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.ACR_REGISTRY }}/yangshengzhou/lucky-sms-backend:${{ github.sha }}
            ${{ secrets.ACR_REGISTRY }}/yangshengzhou/lucky-sms-backend:latest

      # 前端编译打包（生成dist目录）
      - name: 配置Node环境（用于前端编译）
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json

      - name: 安装前端依赖并构建生成dist目录
        run: |
          npm install
          npm run build
        working-directory: ./frontend

      # 步骤3：构建并推送前端镜像
      - name: 构建前端镜像
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.ACR_REGISTRY }}/yangshengzhou/lucky-sms-frontend:${{ github.sha }}
            ${{ secrets.ACR_REGISTRY }}/yangshengzhou/lucky-sms-frontend:latest

      # 步骤4：配置kubectl（确保能连接集群）
      - name: 配置kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          kubectl get nodes  # 验证连接

      # 步骤5：部署MySQL相关资源
      - name: 部署MySQL依赖
        run: |
          kubectl apply -f k8s/mysql-init-configmap.yaml
          kubectl apply -f k8s/mysql.yaml

      # 步骤6：部署后端基础配置
      - name: 部署后端基础配置
        run: kubectl apply -f k8s/backend.yaml

      # 步骤7：更新后端镜像（核心修改4：使用ACR的完整镜像地址）
      - name: 部署后端
        run: |
          kubectl set image deployment/backend backend=${{ secrets.ACR_REGISTRY }}/yangshengzhou/lucky-sms-backend:${{ github.sha }}
          kubectl rollout status deployment/backend

      # 步骤8：部署前端基础配置
      - name: 部署前端基础配置
        run: kubectl apply -f k8s/frontend.yaml

      # 步骤9：更新前端镜像（核心修改5：使用ACR的完整镜像地址）
      - name: 部署前端
        run: |
          kubectl set image deployment/frontend frontend=${{ secrets.ACR_REGISTRY }}/yangshengzhou/lucky-sms-frontend:${{ github.sha }}
          kubectl rollout status deployment/frontend